version: '2.1'
services:
    webserver:
        build: .
        image: de_rec/airflow:latest
        container_name: de_rec_airflow_webserver
        restart: always
        env_file: .env
        depends_on:
            - localstack
            - postgres
        volumes:
          - ../airflow/dags:/opt/airflow/dags
          - ../airflow/plugins:/opt/airflow/plugins
        ports:
            - "8080:8080"
        environment:
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        command: webserver
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
        image: localstack/localstack
        ports:
            - "4566:4566"
            - "4571:4571"
        environment:
            - SERVICES=s3
            - DEFAULT_REGION=eu-north-1
            - DATA_DIR=/var/lib/localstack
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - ./s3_creation.sh:/etc/localstack/init/ready.d/s3_creation.sh
    postgres:
        image: postgres:12.3
        container_name: de_rec_postgres
        env_file: .env
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5433:5432"
    airflow_postgres:
        image: postgres:12.3
        container_name: airflow_postgres
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        ports:
            - "5434:5432"
        volumes:
            - ./airflow_pgdata:/var/lib/postgresql/data